modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mmc"
version="1.6"
displayName="Mekanism More Config"
authors="Tau34"

description='''${mod_description}'''
[[dependencies.mmc]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mmc]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mmc]]
modId="mekanismgenerators"
mandatory=true
versionRange="[10.4.0.14,)"
ordering="NONE"
side="BOTH"